set(SOURCES
	src/CoordiSlots.h
	src/CoordiSlots.cpp
	src/Scaleforms.h
	src/Scaleforms.cpp
	src/Scripts.h
	src/Scripts.cpp
	src/InputMap.h
	src/InputMap.cpp
	src/Utils.h
	src/Utils.cpp
	src/PCH.h
	src/main.cpp
)
